### ISSUE TITLE
Add "info" variant to the StatusIcon component

### ISSUE THREAD

**Issue by mturley** [konveyor/lib-ui#29]
For use in places like https://github.com/konveyor/virt-ui/blob/master/src/app/Plans/components/Wizard/VMConcernsIcon.tsx#L25-L32 and https://github.com/konveyor/virt-ui/pull/163

**Comment by gildub** [comment]
@mturley, even if it's not used for aforementioned PR, I think it'd be good to have it.

**Comment by mturley** [comment]
@gildub yep I agree, there's at least one other place I want to use it. I think maybe we should also add a "loading" variant that puts a spinner in place of the icon and spaces the text next to it properly.
